p = int(input("숫자를 입력하세요: "))
q = int(input("숫자를 입력하세요: "))
print(p+q)
print(p-q)
print(p*q)
print(p/q)
print(p//q)
print(p%q)
print(p**q)
print(p > q)
print(p < q)
print(p == q)
print(p != q)
print(p >= q)
print(p <= q)
print(p > 0 and q > 0)
print(p > 0 or q > 0)
print(not (p > 0))
print(p & q)
print(p | q)
print(p ^ q)
print(~p)
print(p << 2)
print(p >> 2)
import random
print(random.randint(p, q))
print(random.random())
print(random.uniform(p, q))
print(random.choice(range(p, q)))
print(random.shuffle(range(p, q)))
import math
print(math.pow(p,q))
print(math.fabs(p))
print(math.trunc(p))
print(math.log(p))
print(math.sin(math.pi / 2.0))
